name: Terraform

on:
  push:
    branches: [main]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      site_bucket_name: ${{ steps.tf_outputs.outputs.site_bucket_name }}
      cloudfront_distribution_id: ${{ steps.tf_outputs.outputs.cloudfront_distribution_id }}
      api_url: ${{ steps.tf_outputs.outputs.api_url }}
      

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629061775229:role/github-actions-terraform
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      site_bucket_name: ${{ steps.tf_outputs.outputs.site_bucket_name }}
      cloudfront_distribution_id: ${{ steps.tf_outputs.outputs.cloudfront_distribution_id }}
      api_url: ${{ steps.tf_outputs.outputs.api_url }}
      

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629061775229:role/github-actions-terraform
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra

      - name: Export Terraform outputs
        id: tf_outputs
        run: |
          echo "site_bucket_name=$(terraform output -raw site_bucket_name)" >> $GITHUB_OUTPUT
          echo "cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_OUTPUT
          echo "api_url=$(terraform output -raw api_url)" >> $GITHUB_OUTPUT
        working-directory: infra

  web:
    name: Web CI/CD
    needs: terraform-apply
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629061775229:role/github-actions-terraform
          aws-region: us-east-2
    
      - name: Inject API URL into frontend
        run: |
          sed -i "s|__API_BASE_URL__|${{ needs.terraform-apply.outputs.api_url }}|g" app/web/script.js
      
      - name: Upload static site to S3
        run: |
          aws s3 sync app/web s3://${{ needs.terraform-apply.outputs.site_bucket_name }} \
            --delete \
            --cache-control "public, max-age=300"
      
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ needs.terraform-apply.outputs.cloudfront_distribution_id }} \
            --paths "/index.html" "/script.js"
