name: Terraform

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    outputs:
      site_bucket_name: ${{ steps.tf_outputs.outputs.site_bucket_name }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629061775229:role/github-actions-terraform
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra

      - name: Export Terraform outputs
        id: tf_outputs
        run: |
          echo "site_bucket_name=$(terraform output -raw site_bucket_name)" >> $GITHUB_OUTPUT
        working-directory: infra

  web:
    name: Web CI/CD
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629061775229:role/github-actions-terraform
          aws-region: us-east-2
      
      - name: Upload static site to S3
        run: |
          aws s3 sync app/web s3://${{ needs.terraform.outputs.site_bucket_name }} \
            --delete \
            --cache-control "public, max-age=300"
      
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ needs.terraform.outputs.cloudfront_distribution_id }} \
            --paths "/*"

  api:
    name: API CI/CD
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629061775229:role/github-actions-terraform
          aws-region: us-east-2

      - name: Inject API URL into frontend
        run: |
          sed -i "s|__API_BASE_URL__|${{ steps.tf_outputs.outputs.api_base_url }}|g" app/web/script.js



